name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "__Hello_Steps_"
          echo "First output"
          echo "Second output"
          echo "_____________"
      - name: Print Goodbye
        run: |
          echo "__Bye_Steps__"
          echo "Third"
          echo "Fourth"
          echo "_____________"
